### ISSUE TITLE
./mkpkg micro error

### ISSUE THREAD

**Issue by godispy** [mesalock-linux/mesalock-distro#2]
./mkpkg micro
fatal: unable to access 'https://go.googlesource.com/net/': Failed to connect to go.googlesource.com port 443: Connection timed out
Failed to clone 'cmd/micro/vendor/golang.org/x/net' a second time, aborting
package github.com/zyedidia/micro/cmd/micro: exit status 1

**Comment by mssun** [comment]
Sorry, I cannot reproduce your issue, and I can make `micro` package on my device right now.

@godispy BTW, did you have a stable connection to Go server? (i.e., Goole's server)

**Comment by godispy** [comment]
@mssun  Where are you? USA?

**Comment by mssun** [comment]
Yes.

Any update on the issue? Was that caused by the unstable connection? Thanks.
