### ISSUE TITLE
Polish README.md (badges, grammar checks, organization, etc)

### ISSUE THREAD

**Issue by mssun** [mesalock-linux/mesalock-distro#5]
We need to polish the readme file. Now it's lengthy. Here are some thoughts:
  - [x] add badge stating the current release number
  - [x] add badge on the IRC channel
  - [x] go through the whole readme file and check grammars and sentences
  - [x] consider the organization of the readme, and re-organize the outline
  - [x] lists all IRC channels
  - [x] state the git flow developing process

**Comment by wlmnzf** [comment]
Hello,I wonder that wether there are any detail Documents?

**Comment by mssun** [comment]
@wlmnzf Since the project just got started, all details are documented in the README.md file right now. If you think something is missing, please let me know. Thanks.

When the project become larger, we may consider use the wiki page of GitHub (or self-hosted wiki).

**Comment by wlmnzf** [comment]
@mssun OK,Thank you anyway!

**Comment by mssun** [comment]
Done.
