### ISSUE TITLE
mesalock linux ISO

### ISSUE THREAD

**Issue by duramen** [mesalock-linux/mesalock-distro#7]
Can you provide the image?

Compile often wrong。。。。。

**Comment by mssun** [comment]
Thanks for the report. It may be caused by a compilation dependency: `sphinx`. I am working on it.

**Comment by mssun** [comment]
@duramen the issue is fixed by c944bef3edb676908990fadf6b00b320a1cdcc17

The build docker image in DockerHub is also updated. Please pull the latest image. Thanks.

For the pre-compiled images, we plan to release stable and nightly versions in recent days.

**Comment by duramen** [comment]
BTW,   Sphinx>=1.4.3

Otherwise


Extension error:
Could not import extension sphinx.ext.imgmath (exception: No module named imgmath)
