### ISSUE TITLE
How do I install the tar、pdb .....

### ISSUE THREAD

**Issue by duramen** [mesalock-linux/mesalock-distro#8]
I want install the common command, example  tar 、pdb.......

and how ？

**Comment by mssun** [comment]
`tar` package is not in the repo. For now, we only provide tools (packages) written in Rust/Go. For other packages written in unsafe language like `tar`, I am still thinking how to provide them in a more secure way.

In short, we want to isolate the unsafe components and ensure that the memory issues (vulnerabilities) will not affect other safe components. If you have any suggestions, feel free to propose. Thanks.

In the meantime, there is a library https://github.com/mvdnes/zip-rs which provides many zip/unzip algorithms. If you are interested in writing Rust, please consider to write a command line tool.
